import type { ArtPiece } from "@/lib/types";

/**
 * Your art. Shape (image required — art is visual):
 *   { title, artist?, medium?, year?, note?, image, url? }
 * `image` is a path under /public, e.g. "/images/art/piece.jpg".
 */
export const art: ArtPiece[] = [
  {
    title: "Modern Rome",
    artist: "Giovanni Paolo Panini, Italian",
    medium: "Oil on canvas",
    year: "1757",
    image: "/images/art/modern-rome.jpg",
    url: "https://www.metmuseum.org/art/collection/search/437245",
    note: "A pendant to Panini's *Ancient Rome*, this monumental capriccio imagines a grand picture gallery whose walls are hung with views of Rome's most celebrated monuments from the two centuries before it was painted—among them Michelangelo's *Moses* and sculptures by Gian Lorenzo Bernini. An earlier version was commissioned by the comte de Stainville, later duc de Choiseul, the French ambassador to Rome, who is shown seated at the center.",
  },
  {
    title: "The Battle of Alexander at Issus",
    artist: "Albrecht Altdorfer, German",
    medium: "Oil on panel",
    year: "1529",
    image: "/images/art/battle-of-issus.jpg",
    url: "https://en.wikipedia.org/wiki/The_Battle_of_Alexander_at_Issus",
    note: "Altdorfer's masterpiece depicts Alexander the Great's 333 BC victory over Darius III of Persia as a vast “world landscape,” with thousands of tiny soldiers swirling beneath a cosmic sky. Commissioned by Duke William IV of Bavaria, it dresses the armies in sixteenth-century and Ottoman garb, drawing a deliberate parallel between Alexander's campaign and the contemporary European conflict with the Turks.",
  },
  {
    title: "Nighthawks",
    artist: "Edward Hopper, American",
    medium: "Oil on canvas",
    year: "1942",
    image: "/images/art/nighthawks.jpg",
    url: "https://www.artic.edu/artworks/111628/nighthawks",
    note: "Inside a fluorescent-lit all-night diner, three customers and a server sit absorbed in their own thoughts, framed by a sweep of plate glass and an empty street. With spare geometry and no visible door to the outside, Hopper distilled what he called “the loneliness of a large city”—though it was loosely inspired by a restaurant on Greenwich Avenue in New York.",
  },
  {
    title: "Café Terrace at Night",
    artist: "Vincent van Gogh, Dutch",
    medium: "Oil on canvas",
    year: "1888",
    image: "/images/art/cafe-terrace-at-night.jpg",
    url: "https://krollermuller.nl/en/vincent-van-gogh-terrace-of-a-cafe-at-night-place-du-forum-1",
    note: "Painted on the Place du Forum in Arles in September 1888, this is the first of Van Gogh's starry-night scenes—a café terrace glowing warm yellow and orange against a deep blue, star-filled sky. Famously, he rendered the entire night without using any black paint, and the constellations overhead appear as they actually did on the night he worked.",
  },
  {
    title: "The Starry Night",
    artist: "Vincent van Gogh, Dutch",
    medium: "Oil on canvas",
    year: "1889",
    image: "/images/art/starry-night.jpg",
    url: "https://www.moma.org/collection/works/79802",
    note: "Painted from the window of his room at the Saint-Paul-de-Mausole asylum in Saint-Rémy-de-Provence in June 1889, Van Gogh's most famous canvas sets a turbulent, swirling sky over a quiet village he largely imagined. A flame-like cypress climbs toward eleven stars and a glowing crescent moon, the whole scene built from thick, rhythmic strokes of blue and gold. He dismissed it as a failed study in his letters, yet it has become one of the most recognized paintings in the world.",
  },
  {
    title: "Mona Lisa",
    artist: "Leonardo da Vinci, Italian",
    medium: "Oil on poplar panel",
    year: "c. 1503–1519",
    image: "/images/art/mona-lisa.jpg",
    url: "https://en.wikipedia.org/wiki/Mona_Lisa",
    note: "Leonardo began the portrait in Florence around 1503, most likely depicting Lisa Gherardini, wife of the silk merchant Francesco del Giocondo—the source of its Italian name, *La Gioconda*. He never delivered it to the family; instead he carried the unfinished panel with him for years, refining it until his death in France in 1519, after which it passed to King Francis I and into the French royal collection. Napoleon hung it in his own bedroom in the Tuileries Palace for several years before it entered the Louvre, where it drew little notice until its 1911 theft by the Italian handyman Vincenzo Peruggia—and its recovery two years later—turned it into the most famous painting in the world.",
  },
  {
    title: "The Moon",
    artist: "Tarsila do Amaral, Brazilian",
    medium: "Oil on canvas",
    year: "1928",
    image: "/images/art/the-moon.jpg",
    url: "https://www.moma.org/collection/works/199984",
    note: "A dreamlike nocturne by the pioneering Brazilian modernist, painted in 1928 during her Antropofagia phase—the same year she made her celebrated *Abaporu*. A slim golden crescent floats in an undulating blue sky above rolling green hills and a lone cactus, the whole landscape pared down to smooth, sculptural curves. MoMA acquired it in 2019, the first painting by Tarsila to enter the collection.",
  },
  {
    title: "Garden at Sainte-Adresse",
    artist: "Claude Monet, French",
    medium: "Oil on canvas",
    year: "1867",
    image: "/images/art/garden-at-sainte-adresse.jpg",
    url: "https://en.wikipedia.org/wiki/Garden_at_Sainte-Adresse",
    note: "Painted in the summer of 1867 from a flower-filled terrace at the Normandy resort of Sainte-Adresse, near Le Havre, this sunlit scene shows Monet's father and relatives gazing out over the Channel as sailboats and steamers pass. Monet called it “the Chinese painting in which there are flags,” a nod to the flattened space and high horizon he borrowed from Japanese prints; beds of gladioli and nasturtiums blaze against the sea in bands of pure color. An early masterpiece on the cusp of Impressionism, it entered the Met in 1967.",
  },
  {
    title: "Three Jockeys",
    artist: "Edgar Degas, French",
    medium: "Pastel on paper",
    year: "c. 1900",
    image: "/images/art/three-jockeys.jpg",
    url: "https://www.metmuseum.org/art/collection/search/436164",
    note: "The racetrack was one of Degas's lifelong subjects, and here three jockeys rein in their mounts before a race beneath a smudged, glowing sky. Worked in loose, late-career pastel, the scene values color and gesture over finish—by 1900 his eyesight was failing, and he increasingly reused favorite poses drawn from memory and earlier studies.",
  },
  {
    title: "La Grenouillère",
    artist: "Claude Monet, French",
    medium: "Oil on canvas",
    year: "1869",
    image: "/images/art/la-grenouillere.jpg",
    url: "https://www.metmuseum.org/art/collection/search/437135",
    note: "At a popular bathing and boating resort on the Seine near Bougival, Monet and Renoir set up side by side in 1869 and painted the same scene in rapid, broken strokes that catch sunlight flickering across the water. Monet dismissed his versions as “bad sketches” for a larger Salon picture he never completed, yet they are now seen as a birthplace of Impressionism.",
  },
  {
    title: "Capriccio with St. Paul's and Old London Bridge",
    artist: "Antonio Joli, Italian",
    medium: "Oil on canvas",
    year: "c. 1745",
    image: "/images/art/capriccio-st-pauls-london-bridge.jpg",
    url: "https://www.metmuseum.org/art/collection/search/436782",
    note: "A capriccio that frames a faithful view of the Thames—Wren's St. Paul's and the houses crowding Old London Bridge—through a grand colonnade that exists only in the painter's imagination. Joli, a theatrical scene designer who worked in London in the 1740s, delighted in pairing real city vistas with invented classical architecture, the defining conceit of the genre.",
  },
  {
    title: "Still Life with Teapot and Fruit",
    artist: "Paul Gauguin, French",
    medium: "Oil on canvas",
    year: "1896",
    image: "/images/art/still-life-teapot-and-fruit.jpg",
    url: "https://www.metmuseum.org/art/collection/search/437999",
    note: "Painted in Tahiti in 1896, this bold still life sets a blue enamel teapot and ripe mangoes against a flat, patterned ground, the forms ringed in dark outline and filled with unmodulated color in Gauguin's Synthetist manner. He shipped it back to Paris among works meant to assert his vision of a “primitive,” color-driven art far from European convention.",
  },
  {
    title: "Masquerade Ball at the Ritz Hotel, Paris",
    artist: "Raimundo de Madrazo y Garreta, Spanish",
    medium: "Oil on canvas",
    year: "1909",
    image: "/images/art/masquerade-ball-ritz.jpg",
    url: "https://www.metmuseum.org/art/collection/search/436927",
    note: "A glittering costume ball unfolds in the palm-filled interior of the recently opened Ritz, where guests in eighteenth-century dress dance and gossip around a flower-ringed fountain. Madrazo, a Spanish painter long settled in Paris and prized for his polished society scenes, captures the Belle Époque appetite for spectacle and historical fancy dress.",
  },
  {
    title: "Knight before the Charcoal Burner's Hut",
    artist: "Carl Philipp Fohr, German",
    medium: "Oil on canvas",
    year: "1816",
    image: "/images/art/knight-before-the-charcoal-burners-hut.jpg",
    url: "https://en.wikipedia.org/wiki/Karl_Philipp_Fohr",
    note: "A German Romantic forest scene in which a richly dressed knight reins in at the edge of the woods before a charcoal burner's hut, a medieval castle rising through the mist beyond. Fohr painted it in 1816, still in his early twenties and steeped in the era's longing for a chivalric past. He drowned in the Tiber in Rome two years later at just twenty-two, which makes finished oils like this one rare.",
  },
  {
    title: "Entry of the German-English Legion in Hanover",
    artist: "Ernst Hildebrand, German",
    medium: "Oil on canvas",
    year: "c. 1900",
    image: "/images/art/entry-of-the-german-english-legion-in-hanover.jpg",
    url: "https://smb.museum-digital.de/object/142782",
    note: "An oil study for the right-hand panel of a three-part mural Hildebrand painted around 1900 for the boardroom of the Ständehaus in Hanover. It shows the 1816 homecoming of the King's German Legion—Hanoverian troops who had fought Napoleon across Spain, Portugal, and the field of Waterloo—welcomed back through the streets amid flags and palm fronds. The finished murals were lost in the Second World War, so the surviving studies, sent to Berlin for safekeeping in 1908, are all that remains of the composition.",
  },
  {
    title: "Burg Scharfenberg at Night",
    artist: "Ernst Ferdinand Oehme, German",
    medium: "Oil on canvas",
    year: "1827",
    image: "/images/art/burg-scharfenberg-at-night.jpg",
    url: "https://en.wikipedia.org/wiki/Ernst_Ferdinand_Oehme",
    note: "A quintessential German Romantic nocturne: the medieval castle of Scharfenberg, between Dresden and Meissen, glows in golden lamplight out of the dark while a lone rider approaches through gnarled, leafless oaks. Oehme trained under Caspar David Friedrich, and the painting's moonlit mysticism and yearning for the medieval past are unmistakably his master's. It remains among the most admired of his works.",
  },
  {
    title: "The Granite Dish in the Berlin Lustgarten",
    artist: "Johann Erdmann Hummel, German",
    medium: "Oil on canvas",
    year: "1831",
    image: "/images/art/granite-dish-berlin-lustgarten.jpg",
    url: "https://en.wikipedia.org/wiki/Johann_Erdmann_Hummel",
    note: "Hummel—nicknamed “Perspektiv-Hummel” for his obsession with optics—records the colossal polished granite basin, nearly seven meters across, that Christian Gottlieb Cantian's workshop cut for the Lustgarten. He treats it as a marvel of modern engineering and a sly joke at once: the mirror-bright surface reflects the surrounding crowd, the stonemason, and a cavalryman upside down, so all of Berlin society seems to stand on its head. It is a celebrated Biedermeier study of reflection and perspective.",
  },
  {
    title: "The Museum at Le Havre",
    artist: "Claude Monet, French",
    medium: "Oil on canvas",
    year: "1873",
    image: "/images/art/museum-at-le-havre.jpg",
    url: "https://www.nationalgallery.org.uk/paintings/claude-monet-the-museum-at-le-havre",
    note: "Monet set up on the harbor wall at Le Havre, his home port, facing the town's museum of fine arts and library half-hidden behind a thicket of masts and sails. Broken strokes of grayish blue and brown, lifted by flecks of orange, catch the rippling water and reflections under an overcast northern sky. Painted in 1873, the year before the first Impressionist exhibition, it keeps the freshness of a sketch despite its size.",
  },
  {
    title: "Seaport with the Embarkation of the Queen of Sheba",
    artist: "Claude Lorrain, French",
    medium: "Oil on canvas",
    year: "1648",
    image: "/images/art/seaport-embarkation-queen-of-sheba.jpg",
    url: "https://www.nationalgallery.org.uk/paintings/claude-seaport-with-the-embarkation-of-the-queen-of-sheba",
    note: "Claude paints the rare moment of the Queen of Sheba setting out by sea to visit King Solomon, the whole harbor bathed in the soft gold of a rising sun and flanked by the symmetrical classical architecture he perfected in Rome. It was made in 1648 for the Duc de Bouillon, whose name is inscribed on the bottom step, as a pendant to another of his landscapes. Among the first pictures to enter the National Gallery, in 1824, it so moved J. M. W. Turner that he asked to be hung beside it.",
  },
  {
    title: "The Seine at Nanterre",
    artist: "Maurice de Vlaminck, French",
    medium: "Oil on canvas",
    year: "1906–1907",
    image: "/images/art/seine-at-nanterre.jpg",
    url: "https://www.vangoghmuseum.nl/en/collection/s0514S2007",
    note: "A high-Fauvist view of the Seine at Nanterre, then an industrial village outside Paris, built from pure, unmixed color and clashing complementaries. Vlaminck was an outspoken admirer of Van Gogh—you can feel it in the vehement brushwork—and chased what he called a way to “purify” the landscape into raw chromatic force. Fittingly, the canvas now hangs in the Van Gogh Museum in Amsterdam.",
  },
  {
    title: "The Sheepshearer (after Millet)",
    artist: "Vincent van Gogh, Dutch",
    medium: "Oil on canvas",
    year: "1889",
    image: "/images/art/the-sheepshearer-after-millet.jpg",
    url: "https://www.vangoghmuseum.nl/en/collection/s0042V1962",
    note: "One of the color “translations” of Jean-François Millet that Van Gogh made as a patient at the Saint-Rémy asylum, worked up from a black-and-white wood engraving in Millet's *Travaux des champs*. With only the monochrome print to follow, he invented his own palette—tones, as he told his brother Theo, “ranging from lilac to yellow.” Copying Millet, the artist he revered above all others, helped steady him through his recovery.",
  },
  {
    title: "Still Life with Kettle",
    artist: "Paul Cézanne, French",
    medium: "Oil on canvas",
    year: "c. 1867–1869",
    image: "/images/art/still-life-with-kettle.jpg",
    url: "https://artsandculture.google.com/asset/still-life-with-kettle/hAHRMEPj8dZZwA",
    note: "An early, dark-toned still life from Cézanne's pre-Impressionist years, arranging humble things—a blue-gray earthenware kettle, a jar, eggs, onions, and a rumpled cloth—on a bare table against a somber ground. The thick, coarse paint gives the objects real weight, and the deliberately tilted, anti-illusionistic perspective already points toward the structural still lifes of his maturity. It is an early step in the lifelong reinvention of the genre that would make his name.",
  },
  {
    title: "The Rue Montorgueil in Paris, Celebration of June 30, 1878",
    artist: "Claude Monet, French",
    medium: "Oil on canvas",
    year: "1878",
    image: "/images/art/rue-montorgueil-paris.jpg",
    url: "https://artsandculture.google.com/asset/the-rue-montorgueil-in-paris-celebration-of-june-30-1878/hQGKcVaLpt9iCg",
    note: "Monet looked down on the rue Montorgueil from an upper window and dissolved the packed street and its blizzard of red-white-and-blue tricolors into a flicker of quick, broken strokes. The flags marked the government's “Fête de la paix et du travail” on June 30, 1878, staged during the Paris Universal Exhibition as a show of recovery after the defeat of 1870. Often mistaken for a Bastille Day scene, it has a companion view of the nearby rue Saint-Denis.",
  },
  {
    title: "An English Warship Firing a Salute",
    artist: "Willem van de Velde the Younger, Dutch",
    medium: "Oil on canvas",
    year: "1673",
    image: "/images/art/english-warship-firing-a-salute.jpg",
    url: "https://www.nga.gov/artworks/214374-english-warship-firing-salute",
    note: "A three-decked warship rides at anchor and lets off a cloud of cannon smoke in salute, the gun ports along its port side flung open and a flag bearing the cross of St. George streaming from the stern. Van de Velde was the greatest marine painter of the Dutch Golden Age, and he made this picture the year he and his father left Holland to enter the service of Charles II—one of his earliest English works, signed on a fragment of driftwood at lower right, “W. V Velde In Londen 1673.” His exacting rigging and weather, drawn from a lifetime of studies made at sea, set the standard for ship portraiture for a century to come.",
  },
  {
    title: "Imaginary River Landscape",
    artist: "Herman Saftleven, Dutch",
    medium: "Oil on panel",
    year: "1670",
    image: "/images/art/imaginary-river-landscape.jpg",
    url: "https://www.nga.gov/artworks/208068-imaginary-river-landscape",
    note: "One of Herman Saftleven's most delicate Rhineland fantasies, looking down from a high vantage over a meandering river valley that exists nowhere in particular. Precisely drawn travelers, a shepherd, and boatmen working the river occupy a warm, earthy foreground that dissolves, through layer upon layer of atmospheric blue, into distant walled towns, church towers, and villages. A native of Rotterdam who settled in Utrecht, Saftleven traveled the Rhine after the Thirty Years' War ended in 1648, and the journey gave him the fanciful mountainous panoramas—indebted to Pieter Bruegel the Elder's “world landscapes”—that became the finest work of his long career.",
  },
  {
    title: "Salem Cove",
    artist: "Maurice Prendergast, American",
    medium: "Oil on canvas",
    year: "c. 1915–1918",
    image: "/images/art/salem-cove.jpg",
    url: "https://www.nga.gov/artworks/66431-salem-cove",
    note: "A sunny New England shore built up from dabs and patches of color in Prendergast's unmistakable mosaic-like manner, where figures, foliage, water, and sky flatten into a single shimmering, tapestried surface. The lone American member of The Eight and an early champion of European modernism at home, Prendergast spent his late summers in resort towns north of Boston; this is among the finest of the Salem, Massachusetts, scenes he painted between 1914 and 1923, when failing health forced him to put down his brushes.",
  },
];
